### ISSUE TITLE
Polymer 1.0 support

### ISSUE THREAD

**Issue by warpech** [handsontable/hot-table#16]
It would be nice to get support for Polymer 1.0, at least experimentally on a separate branch

**Comment by MetaMemoryT** [comment]
:+1:

**Comment by devmikko** [comment]
:+1:

**Comment by SebastianBoyd** [comment]
+1

**Comment by MetaMemoryT** [comment]
This has been added in: https://github.com/MetaMemoryT/hot-table/tree/polymer-bower-update

**Comment by lukaskrs** [comment]
I couldn't get the one updated by meta to be working. (btw I tried to update the example to polymer 1.0) but yes, hasn't managed to get it working just yet. I don't know how to use github pull /push yet (any tutorial?). so I uploaded the examples for 1.0 here http://s000.tinyupload.com/index.php?file_id=05938535066235762003

**Comment by MetaMemoryT** [comment]
I have merged changes from 0.1.8 release:

https://github.com/MetaMemoryT/hot-table/commit/c8dc60c6ef772dd86855d6f35ac7f294b99566c6

**Comment by devmikko** [comment]
Merged pull request of @MetaMemoryT

**Comment by budnix** [comment]
Released in v0.2.0
