### ISSUE TITLE
Alternate row colors

### ISSUE THREAD

**Issue by devmikko** [handsontable/hot-table#19]
I'm sorry for this noobish question but since migrating to 0.2 (Polymer 1).

How can I implement an alternating row colors.

Is it going to be handled by the renderers?

**Comment by budnix** [comment]
Hi, you are right you can handle this by the renderer like this http://jsfiddle.net/k7w35tgb/1/.

**Comment by devmikko** [comment]
Thanks! It's my fault I removed the double curly brackets since I thought they are referencing to a function.

Can this also be done via the declarative renderers?

**Comment by budnix** [comment]
Unfortunately for now only columns you can declare in declarative way (via `hot-column` - http://hot-table.dev/hot-table/examples/editors.html)

**Comment by devmikko** [comment]
Ok :) Thank you very much.
