### ISSUE TITLE
hot-table not working with Handsontable greater then 0.20.0

### ISSUE THREAD

**Issue by budnix** [handsontable/hot-table#25]
hot-table not working with Handsontable greater then 0.20.0.

**Comment by budnix** [comment]
Fixed in https://github.com/handsontable/handsontable/tree/feature/data-source-issue.

**Comment by warpech** [comment]
Cool! Will you release a new version? Please keep compatibility with Polymer 1.1

**Comment by budnix** [comment]
I will release new version probably on the beginning of the next week. Currently develop branch is for sure compatible with Polymer 1.2.3 and 1.1.5.
