### ISSUE TITLE
autocomplete field sometimes making the HOT cursor stuck

### ISSUE THREAD

**Issue by lukaskrs** [handsontable/hot-table#3]
how to reproduce issue:
- double click an autocomplete field
- type any text that's not valid and backspace to delete previous character won't work
- and when I try to move the cursor out of the field, I got this error in the console

 Uncaught TypeError: Cannot read property 'getInstance' of undefined handsontable.full.js:6809
line where the error occur: [  var innerHOT = editor.htEditor.getInstance(); ]
function that's has bug: handsontable.full.js:6809 - onBeforeKeyDown function

I understand this might be related with handsontable bug, but I think the issue is somewhere related with the polymer implementation preventing HOT to get the required node / variable since shadow DOM might have a bit structure differences.

![stuck cursor](https://cloud.githubusercontent.com/assets/8187899/5973687/c70f3af4-a89d-11e4-9427-3f4d93c67223.JPG)

**Comment by budnix** [comment]
Thanks for bug reporting. 

At the moment, we have released a new version of Handsontable (0.12.6). Simple `bower update` should resolve this bug.
