### ISSUE TITLE
How can I change css styles of the table?

### ISSUE THREAD

**Issue by Sue1024** [handsontable/hot-table#42]
Nothing happened when I change some css properties on <hot-table> or < hot-column>

**Comment by warpech** [comment]
It doesn't work this way. `<hot-column>` is just used to provide configuration for `<hot-table>`. 

The styles of the table come are defined in Shadow DOM of `<hot-table>`. To affect the Shadow DOM styles of `<hot-table>` you would need to fork this repo and make custom edits to `hot-table-style.html`.

Sorry for a late answer!
