### ISSUE TITLE
Make this element compatible with Polymer 2

### ISSUE THREAD

**Issue by warpech** [handsontable/hot-table#44]
It should be upgraded to be a hybrid element, compatible with Polymer 1 and 2:

https://www.polymer-project.org/2.0/docs/devguide/hybrid-elements

**Comment by budnix** [comment]
Hi @warpech, We've released the new version of `hot-table` (see https://github.com/handsontable/hot-table/releases/tag/v0.6.0). That release adds expected support to hybrid elements (I've tested it with Polymer 1.6 to 2.0).

If you find any issue please leave a comment or report a separate issue.

**Comment by warpech** [comment]
Thanks, you're the greatest!

**Comment by warpech** [comment]
This component is still using `<content>` tag. To be a Polymer 2.0, it should use `<slot>`:

> Hybrid elements must use the shadow DOM v1 style <slot> element and ::slotted() CSS selector in place of the <content> element and ::content selector from shadow DOM v0.

https://www.polymer-project.org/2.0/docs/devguide/hybrid-elements

@budnix can you pls take a look?

**Comment by budnix** [comment]
Hi, @warpech where did you see the warning about using `<content>` tag? Looking through the latest version of the source code I see only `<slot>` tags (https://github.com/handsontable/hot-table/blob/master/src/hot-column.html, https://github.com/handsontable/hot-table/blob/master/src/hot-table.html)

**Comment by warpech** [comment]
You are right! It seems that it is only in two demos:

- https://github.com/handsontable/hot-table/blob/2f98836226618170d9a4d76867e39eb1d50e8cd1/examples/components/dashboard-tile.html#L39
- https://github.com/handsontable/hot-table/blob/2f98836226618170d9a4d76867e39eb1d50e8cd1/examples/components/dashboard-demo.html#L50

**Comment by budnix** [comment]
Thanks for investigation! Components that use an older API was fixed in [0.6.1](https://github.com/handsontable/hot-table/releases/tag/v0.6.1). Gh Pages was updated as well.

**Comment by warpech** [comment]
Thanks!!!
