### ISSUE TITLE
Programatically close cell editor

### ISSUE THREAD

**Issue by phamvanthanh** [handsontable/hot-table#45]
Hi @wszymanski,
I trigger cell to open i dialog and wanted to close the cell editor right after dialog is opened, which function will help me to do that?

**Comment by warpech** [comment]
Use the `destroyEditor` method as in:

```
document.querySelector("hot-table").hot.destroyEditor();
```

See: https://docs.handsontable.com/0.35.1/Core.html#destroyEditor

Sorry for late response!
