### ISSUE TITLE
Context menu does not open up for touch screen mobile

### ISSUE THREAD

**Issue by pawansalunke57** [handsontable/hot-table#55]
Context menu is not opening on touchscreen mobile , same is working on desktop browsers.
![image](https://user-images.githubusercontent.com/78777452/107317153-1562e580-6ac0-11eb-9ca0-3240a45c0248.png)

**Comment by AMBudnik** [comment]
Hi @pawansalunke57 

Thank you for sharing but this issue has been already raised here https://github.com/handsontable/handsontable/issues/5171 and it became a part of the scope of the general issue called Interoperability problems using Mobile devices and some core features, reported at [#7520](https://github.com/handsontable/handsontable/issues/5171)

I will close this topic as a duplicate and inform you after fixing the main subject at https://github.com/handsontable/handsontable/issues/5171
