### ISSUE TITLE
Installation in Polymer 3 project.

### ISSUE THREAD

**Issue by zhangwu-engineer** [handsontable/hot-table#56]
Hi, hot-table team. Thanks for a great tool.
In my project, I tried to use this package for a purpose of excel grid view.

- Does it work well with Polymer 3?
- Do I need to embed polyfill js file and html file for usage?
- I tried to use <hot-table> inside the render section but nothing happens. It is not bound as shadow dom and I can't see anything on the screen.

Please help me for those issues.
Great regards!

**Comment by AMBudnik** [comment]
Hi @zhangwu-engineer 

we stopped developing this project some time ago (in 2018). It hasn't been tested with Polymer 3.

**Comment by warpech** [comment]
Like @AMBudnik said, this component was not upgraded to Polymer 3. I suggest to make your own wrapper for Polymer 3 that uses the JavaScript version of Handsontable. It is definitely possible but it is hard for me to estimate the effort.

Thanks for your interest in Handsontable and Polymer. I wish Polymer was more popular.
