### ISSUE TITLE
Fatal Error on press backspace when after selected;

### ISSUE THREAD

**Issue by lucasfanning** [handsontable/hot-table#7]
Fatal Error on press backspace when after cell is selected;
The provable problem is the shadowDom, as tested here.

**Comment by lucasfanning** [comment]
if I use for lightDom:

Polymer({
  parseDeclaration: function(elementElement) {
    var template = this.fetchTemplate(elementElement);
    if (template) {
      var root = this.lightFromTemplate(template);
    }
  }
});

for each component util the root, the problem is "solved",
but it is a bug, we need correct it.

**Comment by budnix** [comment]
Could you try hot-table with newest version of Handsontable 0.12.6 (`bower update`)?. In this version we have fixed some bugs related with web components.

**Comment by devmikko** [comment]
Works ok now after updating the Handsontable.
