### ISSUE TITLE
Datepicker is not showing

### ISSUE THREAD

**Issue by devmikko** [handsontable/hot-table#8]
Datepicker is not showing despite moment.js and pikaday.js was imported.

![screenshot_1](https://cloud.githubusercontent.com/assets/6368863/6321482/35c0a688-bb39-11e4-863e-1192e0936e08.png)

**Comment by budnix** [comment]
This should be fixed in version 0.13.0 which has been just released.

**Comment by devmikko** [comment]
Awesome! It is working now.
