### ISSUE TITLE
Inputs are losing their focus when CTRL is pressed

### ISSUE THREAD

**Issue by devmikko** [handsontable/hot-table#9]
`<paper-input>` or `<input>` (or maybe other webcomponents inputs) are losing their current focus when CTRL is pressed

```
<paper-input floatinglabel label='Text'></paper-input>
<hot-table datarows="{{itemsArray}}"></hot-table>
```

**Comment by budnix** [comment]
This should be fixed now in version 0.14.0 of Handsontable which has been just released.
